Socket.io v3.0
forus-labs/poke pull request #1
Opened 2020-11-22 09:20 UTC by Daviiddoo

- [ ] Removed testing code

- [ ] Redis support

- [ ] passing of Protobuf data via `ArrayBuffer`

2020-11-22 15:45 UTC, kawaijoe requested changes
Have yet to review `src/server.ts`. WIll look into it later.

2020-11-22 15:45 UTC, kawaijoe commented on .gitignore
> +.idea
Can we use a more legit .gitignore?

https://github.com/microsoft/TypeScript-Node-Starter/blob/master/.gitignore

2020-11-22 15:45 UTC, kawaijoe commented on .eslintignore
> +# don't ever lint node_modules
Same here:

https://github.com/microsoft/TypeScript-Node-Starter/blob/master/.eslintignore

2020-11-22 15:45 UTC, kawaijoe commented on tsconfig.json
> +
May I know where you referenced this file?

2020-11-22 15:45 UTC, kawaijoe commented on .eslintrc.js
> +module.exports = {
May I know where you referenced this file?

2020-11-22 15:45 UTC, kawaijoe commented on Procfile
> +web: npm start
Procfile is only used for Heruko. Do you think it should be in the repo? @Pante

2020-11-23 01:53 UTC, Pante commented on Procfile
> +web: npm start
imo deployment files should not be in a repository if it can be helped.

2020-11-23 02:13 UTC, Pante requested changes

2020-11-23 02:13 UTC, Pante commented on src/server.ts
> +interface ExtendedSocket extends Socket {
Maybe a better name will be `UserSocket`, `VerifiedSocket`, `IdentifiedSocket`?

2020-11-23 02:13 UTC, Pante commented on src/server.ts
> +io.adapter(redisAdapter);
why not just directly do `io.adapter(createAdapter(process.env.REDIS_URL, { key: process.env.REDIS_KEY });`? That way we don't have to create a constant for `redisAdapter`, it seems to be only used here anyways.

2020-11-23 02:13 UTC, Pante commented on src/server.ts
> +        privateKey: process.env.PRIVATE_KEY.replace(/\\n/g, '\n'),
Please leave a comment here to document why we need to replace `...` with `\n`.

2020-11-23 02:13 UTC, Pante commented on src/server.ts
> +    //uuid of firebase user
Comment is kinda redundant imo

2020-11-23 02:13 UTC, Pante commented on src/server.ts
> +        // join User room
Comment is kinda redundant imo

2020-11-23 02:13 UTC, Pante commented on src/server.ts
> +    //on disconnect
This one too

2020-11-23 02:13 UTC, Pante commented on src/server.ts
> +        // on update
This too

2020-11-23 02:13 UTC, Pante commented on src/server.ts
> +                err.message += ` - User ID could not be verified: ${FirebaseError}`;
Error message is slightly misleading, it's not the User ID but rather the token that could not be verified.

2020-11-23 02:13 UTC, Pante commented on src/server.ts
> +                err.message += ` - User ID could not be verified: ${FirebaseError}`;
FireBaseError is a variable, shouldn't it be camelCase?

2020-11-23 02:13 UTC, Pante commented on src/server.ts
> +import * as admin from "firebase-admin";
Curious but is there a need/ is it recommended to prefix this import with `admin`?

2020-11-23 02:13 UTC, Pante commented on src/server.ts
> +            socket.broadcast.to(uuid).emit(UPDATE, data);
should we log this?

2020-11-23 02:13 UTC, Pante commented on src/server.ts
> +        console.log('user disconnected: ', socket.id);
If we're logging when the user disconnected, should we log when they connect too?

2020-11-23 02:13 UTC, Pante commented on src/server.ts
> +        console.log('user disconnected: ', socket.id);
Also nitpick, but imo the format `<user id> has disconnected` is clearer

2020-11-23 06:20 UTC, kawaijoe requested changes

2020-11-23 06:20 UTC, kawaijoe commented on src/server.ts
> +const redisAdapter: RedisAdapter = createAdapter(process.env.REDIS_URL, { key: process.env.REDIS_KEY });
Is there a reason why the type is explicitly defined here?

2020-11-23 06:20 UTC, kawaijoe commented on src/server.ts
> +                console.log(err.message);
I believe this is an error. Use `console.error(...)`

https://nodejs.org/api/console.html#console_console_error_data_args

2020-11-23 06:20 UTC, kawaijoe commented on src/server.ts
> +            socket.broadcast.to(uuid).emit(UPDATE, data);
I think that's a good idea

2020-11-23 06:20 UTC, kawaijoe commented on src/server.ts
> +const CONNECTION = 'connection';
I personally would use a string enum for this.

https://www.typescriptlang.org/docs/handbook/enums.html

2020-11-24 04:48 UTC, Daviiddoo commented on .eslintrc.js
> +module.exports = {
I referenced this from the main typescript-eslint repo on github

https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md

2020-11-24 04:52 UTC, Daviiddoo commented on tsconfig.json
> +
I referenced the file from the typescript-node-starter repo

https://github.com/microsoft/TypeScript-Node-Starter/blob/master/tsconfig.json

2020-11-24 05:32 UTC, Daviiddoo commented on Procfile
> +web: npm start
Did I add it correctly?

2020-11-24 05:34 UTC, Daviiddoo commented on src/server.ts
> +                err.message += ` - User ID could not be verified: ${FirebaseError}`;
FireBaseError or FirebaseError? 

I mean Firebase is one word to me

2020-11-24 05:44 UTC, Daviiddoo commented on src/server.ts
> +import * as admin from "firebase-admin";
`import admin from "firebase-admin"`

you prefer this?

2020-11-24 06:10 UTC, Pante commented on src/server.ts
> +                err.message += ` - User ID could not be verified: ${FirebaseError}`;
The first one

2020-11-24 07:24 UTC, Pante commented on src/server.ts
> +import * as admin from "firebase-admin";
What I meant was whether there is a need to create a `admin` prefix for all imports from `firebase-admin`.

2020-11-25 08:00 UTC, kawaijoe commented on Procfile
> +web: npm start
Yes you did, but since the file is currently tracked by git, you will need to untrack the file and commit again.

2020-11-25 08:20 UTC, kawaijoe requested changes

2020-11-25 08:20 UTC, kawaijoe commented on src/server.ts
> +        console.log('user disconnected: ', socket.id);
Wait wait, I'm confused, why is there two `console.log(...)` for the same thing.

2020-11-25 08:20 UTC, kawaijoe commented on src/server.ts
> +import * as admin from "firebase-admin";
Could you please document the required environment variables in the README.md file? I realized that there isn't any documentation on what env vars are required.

2020-11-25 08:20 UTC, kawaijoe commented on src/server.ts
> +io.adapter(createAdapter(process.env.REDIS_URL, { key: process.env.REDIS_KEY }));
Just curious, what happens if we decide not to add Redis? I think this application might crash.

If so, could you include some checker and logs for this use case?

2020-11-25 08:20 UTC, kawaijoe commented on src/server.ts
> +    const err = new Error('Authentication Failed');
Let's avoid using the short form. If it's an error variable, just name it `error` instead of `err` or `e`. There are exceptions such as a try-catch statement (where `e` might be more appropriate) but that's the general rule of thumb.

2020-11-25 08:20 UTC, kawaijoe commented on src/server.ts
> +        console.log('user disconnected: ', socket.id);
Also, I don't think @Pante meant to add the `<>` inside. HAHA

2020-11-25 08:20 UTC, kawaijoe commented on src/server.ts
> +            console.log(`updating <${socket.id}> group...`)
@Pante Do you have any thoughts on how the logs should be structured? I think it can be done in two different ways.

1) Human readable
<id> has broadcast an update

2) Machine readable
ON UPDATE - <id>

2020-11-26 01:48 UTC, Pante commented on src/server.ts
> +            console.log(`updating <${socket.id}> group...`)
I personally think it should be leaning towards being more human readable

2020-11-26 08:45 UTC, Daviiddoo commented on src/server.ts
> +import * as admin from "firebase-admin";
Is this better?

2020-11-29 15:05 UTC, Pante commented on src/server.ts
> +import * as admin from "firebase-admin";
Yup

2020-11-29 15:07 UTC, Pante commented on README.md
> +| Private key | generated by the firebase project for setting up firebase admin sdk. |
I personally will put the actual key inside a `code block`, it should be clearer in my opinion.

2020-11-30 00:49 UTC, Daviiddoo commented on README.md
> +| Private key | generated by the firebase project for setting up firebase admin sdk. |
Actual key?

2020-11-30 14:37 UTC, Pante requested changes

2020-11-30 14:37 UTC, Pante commented on README.md
> +| Private key | generated by the firebase project for setting up firebase admin sdk. |
Like what's actually used inside the code, i.e. `private key` will most likely be called `PRIVATE_KEY` or something along those lines.

2020-11-30 14:37 UTC, Pante commented on README.md
> +| Private key | generated by the firebase project for setting up firebase admin sdk. |
I think it will be better if you noted which keys are required and optional respectively.

2020-11-30 14:37 UTC, Pante commented on README.md
> +| Client Email | firebase service account email. |
The capitalization is not consistent throughout the table.

2020-11-30 14:37 UTC, Pante commented on README.md
> +| Project Id | A user-assigned unique identifier for the firebase project, mainly used as a convenience alias to referece the firebase project. |
Perhaps the description can be shorten to `A Firebase project's ID`?

2020-11-30 14:37 UTC, Pante commented on package.json
> +    "name": "socket-server-ts",
I don't think the `-ts` suffix is necessary, also, would it be better if it was called `poke`?

2020-11-30 14:37 UTC, Pante commented on package.json
> +    "dependencies": {
Please remind me to enable dependabot for this repository later.

2020-11-30 14:37 UTC, Pante commented on src/server.ts
> +import { initializeApp, auth, FirebaseError, credential } from "firebase-admin";
nitpick, but please sort the imports in ascending alphabetical order please

2020-11-30 14:37 UTC, Pante commented on src/server.ts
> +    console.log('Redis support enabled');
nitpick, but I think `Enabled Redis` would be nicer.

2020-11-30 14:37 UTC, Pante commented on src/server.ts
> +        // Private key is sanitized for Heroku deployment by replacing \\n characters with \n
I don't think sanitized is the right word to describe it in this context, thoughts @kawaijoe?

2020-11-30 14:37 UTC, Pante commented on src/server.ts
> +    const error = new Error('Authentication Failed');
I don't think we should create an error so eagerly. It should only be created when we know that verification has failed.

2020-11-30 14:37 UTC, Pante commented on src/server.ts
> +    const error = new Error('Authentication Failed');
I don't think using an `Error` type is appropriate. It will be better if a `AuthenticationError` type that extends `Error` was declared and used here instead. This will allow us to omit the `Authentication Failed` prefix since that information has been encoded inside the type itself.

2020-11-30 14:37 UTC, Pante commented on src/server.ts
> +                console.log(`${socket.id} token was verified succesfully`);
I think `Successfully verified token for ${socket.id}` is better.

2020-11-30 14:37 UTC, Pante commented on src/server.ts
> +            }).catch((FireBaseError: FirebaseError) => {
`catch((FireBaseError: FirebaseError)` does not follow camelCase naming convention for variables. Aren't variable declarations usually `<name>: <type>`? In this case both name and type are capitalized.

2020-11-30 14:37 UTC, Pante commented on src/server.ts
> +                error.message += ` - Token could not be verified: ${FireBaseError}`;
Would it be better if we created a `InvalidTokenError` that extends the `AuthenticationError` mentioned above?

2020-11-30 14:37 UTC, Pante commented on src/server.ts
> +        error.message += ' - InvalidArgumentException, Token is null or empty';
Again this goes against what I mentioned above

2020-12-01 01:04 UTC, kawaijoe commented on package.json
> +    "dependencies": {
Created an issue for it

2020-12-01 01:37 UTC, kawaijoe requested changes

2020-12-01 01:37 UTC, kawaijoe commented on README.md
> +| Code | Description |
Isn't it more of Environment and Description?

2020-12-01 01:37 UTC, kawaijoe commented on src/server.ts
> +    console.log('Enabled Redis');
Nitpick, I would name it 'Redis Enabled'.

2020-12-01 01:37 UTC, kawaijoe commented on src/server.ts
> +    console.log(`${socket.id} has connected`);
Do you think the `uuid` is more relevant compared to the `socket.id`? @Pante

2020-12-01 01:37 UTC, kawaijoe commented on src/server.ts
> +                console.error(error.message);
If we're logging the error, don't you think the `id` is important?

2020-12-01 01:37 UTC, kawaijoe commented on src/server.ts
> +    const uuid = socket.uuid;
The additional whitespace or lack thereof is kinda triggering.

2020-12-01 01:44 UTC, kawaijoe commented on src/server.ts
> +        // Private key is sanitized for Heroku deployment by replacing \\n characters with \n
It might not be the best word, but it's fairly clear imo.

2020-12-01 02:31 UTC, Pante commented on src/server.ts
> +    console.log(`${socket.id} has connected`);
That's a good point, the UUID should be logged instead.

2020-12-01 02:31 UTC, Pante commented on src/server.ts
> +    console.log('Enabled Redis');
Personally I prefer `Enabled Redis`

2020-12-01 02:35 UTC, Pante commented on src/server.ts
> +        // Private key is sanitized for Heroku deployment by replacing \\n characters with \n
Fair enough

2020-12-01 02:35 UTC, kawaijoe commented on src/server.ts
> +    console.log('Enabled Redis');
I guess it's a small thing. Will be resolving the issue then.

2020-12-01 02:36 UTC, kawaijoe commented on src/server.ts
> +    console.log(`${socket.id} has connected`);
@Daviiddoo Could you please update all of the ids?

2020-12-01 02:41 UTC, Pante requested changes

2020-12-01 02:41 UTC, Pante commented on src/server.ts
> +class InvalidArgument extends Error {
I think this `InvalidToken` and `InvalidArgument` can be merged.

2020-12-01 02:41 UTC, Pante commented on src/server.ts
> +class InvalidArgument extends Error {
In general for errors, I think it would be better to suffix it with `Error`, i.e. `InvalidTokenError` or `InvalidArgumentError`, anyways looking at it again, maybe `AuthenticationError`will be better?

2020-12-01 02:41 UTC, Pante commented on src/server.ts
> +                console.error(error.message);
I think the message can be changed to `<socket.uuid>'s token could not be verified: <error>`

2020-12-02 11:16 UTC, Pante requested changes

2020-12-02 11:16 UTC, Pante commented on README.md
> +| Environment | Description |
Nitpick I think environment variable will be a better header

2020-12-02 11:16 UTC, Pante commented on src/server.ts
> +class InvalidArgumentError extends Error {
I don’t think InvalidArgumentError is needed, we can just throw an AuthenticationError in both the current scenarios.

2020-12-02 11:16 UTC, Pante commented on src/server.ts
> +        const error = new InvalidArgumentError('Token is null or empty');
I think it can be shorten to ‘Token is invalid’

2020-12-16 11:56 UTC, kawaijoe requested changes
Before I can start my review, I will require you to fix your file structure.

May I know why are all the files in the root directory? In addition, it doesn't make sense to add the environment variables in the generic README.md in the root directory. I believe that it is only specific to the server.

2020-12-27 13:56 UTC, kawaijoe requested changes

2020-12-27 13:56 UTC, kawaijoe commented on server/src/connection.ts
> +// Autheticates a client using its token.
Are you missing a space here?

2020-12-27 13:56 UTC, kawaijoe commented on server/src/server.ts
> +// Launch http server that listens to port number specified environment variables.
Missing a space here?

2020-12-27 13:56 UTC, kawaijoe commented on server/src/connection.ts
> +    console.log(`${uuid} has connected`);
@forus-labs/open-sauce Do you think we should add both the `uuid` and socket id for debugging purposes? It might be useful to help identify the different devices.

2020-12-27 13:56 UTC, kawaijoe commented on server/src/connection.ts
> +    if (uuid) {
I think this checks if `uuid` is null. In what cases will `uuid` not exist?

2020-12-27 13:56 UTC, kawaijoe commented on server/src/connection.ts
> +            const error = new AuthenticationError(`Firebase${e}`);
The formatting for the error message seems a bit off. I'm not sure if it is necessary to add the `Firebase` prefix, could you shed some light in this regard?

Assuming that it is helpful, I think you should add some sort of separator/space so it is human readable.
Eg. ```new AuthenticationError(`Firebase: ${e}`);```

2020-12-27 13:56 UTC, kawaijoe commented on server/test/connection.test.ts
> +    test('is successful', done => {
Nitpick but can we add spacing between the tests? It feels off

On a side note, it's quite inconsistent as well. The test below does have a space.

2020-12-27 13:56 UTC, kawaijoe commented on server/test/connection.test.ts
> +        const [arg] = capture(mockedSocket.join).last();
Is there a more descriptive way to label `arg`? It's not exactly clear to me what it is.

2020-12-27 13:56 UTC, kawaijoe commented on server/test/connection.test.ts
> +        const [arg1, lambda] = capture(mockedSocket.on).first();
Same issue here.

2020-12-27 13:56 UTC, kawaijoe commented on server/test/connection.test.ts
> +describe('Authenticate', () => {
Personally, I don't see why groups should be named any differently from each test. In this scenario, I would name it `authentication` or `on authentication`. Any thoughts @forus-labs/open-sauce

2020-12-27 13:56 UTC, kawaijoe commented on server/test/connection.test.ts
> +    test('failed from invalid token', done => {
I don't think tests should be in the past tense. It adds an unnecessary layer of complexity.

A quick look at the Jest documentation shows that they don't follow this practice!
https://jestjs.io/docs/en/setup-teardown

2020-12-27 13:56 UTC, kawaijoe commented on server/test/connection.test.ts
> +    beforeEach(() => {
I noticed that both `beforeEach()` are essentially the same. Will it work if we just placed one function outside of the `describe()`.

2020-12-28 04:50 UTC, Pante requested changes

2020-12-28 04:50 UTC, Pante commented on server/src/connection.ts
> +    console.log(`${uuid} has connected`);
I personally don't see how a Socket ID will help with debugging in this particular case.

2020-12-28 04:50 UTC, Pante commented on server/src/connection.ts
> +            console.log(`${uuid} group was updated`);
Nitpick, but I think we should follow the socket IO terminology and replace "group" with "room".

2020-12-28 04:50 UTC, Pante commented on server/src/connection.ts
> +        socket.on(Event.UPDATE, (data: ArrayBuffer) => {
Do we need to explicitly type `data`?

2020-12-28 04:50 UTC, Pante commented on server/src/connection.ts
> +export { authenticate, connect, Event, UserSocket, AuthenticationError }
I would prefer it if the export statement was at the top of the file, after all the imports.

2020-12-28 04:50 UTC, Pante commented on server/test/connection.test.ts
> +// Mocked Socket
I honestly don't think these comments are necessary, it should be already clear from the code what the socket is.

2020-12-28 04:50 UTC, Pante commented on server/test/connection.test.ts
> +const mockedSocket = mock<UserSocket>();
I disagree with prefixing everything with `mocked` and I think it can be omitted.

2020-12-28 04:50 UTC, Pante commented on server/test/connection.test.ts
> +    return { auth: { token: tokenId }, query: undefined, address: undefined, headers: undefined, issued: undefined, secure: undefined, time: undefined, url: undefined, xdomain: undefined };
Is it necessary to declare all the fields that are not used by the tests?

2020-12-28 04:50 UTC, Pante commented on server/test/connection.test.ts
> +// Mocked Auth
Again, I think the comment can be removed.

2020-12-28 04:50 UTC, Pante commented on server/test/connection.test.ts
> +when(mockedAuth.verifyIdToken('suKSRWjRyzbZAEMTY4i0mi1jan83')).thenResolve(mockedDecodedToken);
I believe it is best practice to move all these initialization behaviour into a `beforeEach(...)` method.

2020-12-28 04:50 UTC, Pante commented on server/test/connection.test.ts
> +describe('Authenticate', () => {
I think it should be named `authentication` too.

2020-12-28 04:50 UTC, Pante commented on server/test/connection.test.ts
> +        const mSocket = instance(mockedSocket);
Again, I really dislike prefixing with `m`. Whether it is mocked or not is an implementation detail, we should not encode it into our variable names.

2020-12-28 04:50 UTC, Pante commented on server/test/connection.test.ts
> +            try {
Please remove all debug comments.

2020-12-28 08:57 UTC, Daviiddoo commented on server/src/connection.ts
> +    if (uuid) {
if the client does not send UUID correctly

2020-12-28 15:00 UTC, Daviiddoo commented on server/src/connection.ts
> +            const error = new AuthenticationError(`Firebase${e}`);
the `e` prints out a normal error message. So with the current implementation, the error message printed would appear as follows, Eg. `FirebaseError: Token was Invalid`

2020-12-28 15:13 UTC, Pante commented on server/test/connection.test.ts
> +describe('Authenticate', () => {
After spending more time on this, I feel that the name should follow the name of the method under test, in this case, “authenticate”, with a lowercase a.

2020-12-28 15:30 UTC, Daviiddoo commented on server/test/connection.test.ts
> +    return { auth: { token: tokenId }, query: undefined, address: undefined, headers: undefined, issued: undefined, secure: undefined, time: undefined, url: undefined, xdomain: undefined };
Yes, it will error out saying the argument being returned does not conform to the type specified

2020-12-28 15:39 UTC, Daviiddoo commented on server/test/connection.test.ts
> +            try {
I thought this was a form of documentation of the tests

2020-12-28 16:07 UTC, Daviiddoo commented on server/src/connection.ts
> +export { authenticate, connect, Event, UserSocket, AuthenticationError }
Application crashes with `ReferenceError: Cannot access 'AuthenticationError' before initialization`

2020-12-29 05:35 UTC, Pante commented on server/src/connection.ts
> +export { authenticate, connect, Event, UserSocket, AuthenticationError }
In that case, I think we should prefix the functions & types with `export` rather than use the export statement, It feels really odd that the export statement needs to be at the end.

2020-12-29 07:57 UTC, kawaijoe commented on server/src/connection.ts
> +    console.log(`${uuid} has connected`);
It'll help us identify the different devices connected. The UUID isn't unique over multiple devices.

In addition, I don't think it should be added only for this particular case, but all of the debug statements.

2020-12-29 08:23 UTC, kawaijoe requested changes

2020-12-29 08:23 UTC, kawaijoe commented on server/src/connection.ts
> +export { authenticate, connect, Event, UserSocket, AuthenticationError }
Apart from the above mentioned by @Pante, I would like to point out that a semi-colon is missing for some reason.

2020-12-29 08:23 UTC, kawaijoe commented on server/src/connection.ts
> +            const error = new AuthenticationError(`Firebase${e}`);
In that case, I think there should be a comment explaining why it was implemented this way. It wasn't clear at a glance.

2020-12-29 08:23 UTC, kawaijoe commented on server/src/connection.ts
> +    if (uuid) {
Isn't that what the error handling on `authenticate()` is for? I do not see any benefits of having this.

2020-12-29 08:23 UTC, kawaijoe commented on server/src/connection.ts
> +    if (uuid) {
Actually, this is way worse than it seems, it's completely swallowing the error message and it doesn't even inform the client what went wrong. At the very least, the server should disconnect the user.

2020-12-29 19:24 UTC, Daviiddoo commented on server/src/connection.ts
> +    if (uuid) {
oh, my mistake, I misinterpreted the question. You are right, there are no cases that uuid does not exist

2020-12-30 13:11 UTC, Pante commented on server/src/connection.ts
> +    console.log(`${uuid} has connected`);
It will help us identify the different devices, but what use case would that help debug? From my understanding, socket IDs will not always specifically be tied to a certain device, it's just for a particular socket session.

2020-12-31 04:32 UTC, kawaijoe commented on server/src/connection.ts
> +    if (uuid) {
If that's the case, is there a point to have that if check?

2021-01-01 04:56 UTC, kawaijoe commented on server/src/connection.ts
> +    console.log(`${uuid} has connected`);
A particular socket generally means a specific device. Unless the device got disconnected/reconnected for some reason, in which case, it will be logged as well.

For debugging, pretty much everything. We'll be able to observe which device is broadcasting what message, which is very important considering all of the UUIDs will be the same.

2021-01-01 05:50 UTC, Pante commented on server/src/connection.ts
> +    console.log(`${uuid} has connected`);
Fair enough, let's add the socket ID too then.

2021-01-01 14:45 UTC, Pante commented on server/src/connection.ts
> +    console.log(`${uuid}<${socket.id}> has connected`);
I think you're missing a space

2021-01-02 06:55 UTC, kawaijoe requested changes
Generally looking pretty good, just a few minor things.

2021-01-02 06:55 UTC, kawaijoe commented on server/src/connection.ts
> +        console.log(`${uuid}<${socket.id}> room was updated`);
Nitpick, `${uuid}<${socket.id}> room is updated`

2021-01-02 06:55 UTC, kawaijoe commented on server/test/connection.test.ts
> +        const [event, lambda] = capture(mockedSocket.on).first();
Personally would name this a `callback` rather than a `lambda`. Any thoughts @Pante

2021-01-04 14:44 UTC, Pante requested changes

2021-01-04 14:44 UTC, Pante commented on server/src/connection.ts
> +            const error = new AuthenticationError(`Firebase${e}`);
I'm reopening this issue, after some further thought it seems really weird, If the error message produced by `${e}` is `FirebaseError: Token was Invalid`, then why do we still need to prefix it with `Firebase`?

If it doesn't, I think that, since we already prefix it with `Firebase`, I think it will be better to use `${e.message}` instead.

The comment could be removed either ways, but I think it is necessary to highlight that the comment isn't good. It doesn't explain _why_ the formatting is implemented in such a way. There's no context around the example, it isn't really helpful.

2021-01-04 14:44 UTC, Pante commented on server/src/connection.ts
> +    constructor(message: string) {
I seem to have missed this out, but the constructor's missing documentation.

2021-01-04 14:44 UTC, Pante commented on server/test/connection.test.ts
> +const mockedSocket = mock<UserSocket>();
Nitpick, but I think `mock` prefix would be nicer than `mocked`.

2021-01-04 14:44 UTC, Pante commented on server/test/connection.test.ts
> +        expect(uuid).toBe('suKSRWjRyzbZAEMTY4i0mi1jan83');
This particular string seems to be used around alot, would it better if it was turned into a constant?

2021-01-05 05:17 UTC, Daviiddoo commented on server/src/connection.ts
> +        console.log(`${uuid} <${socket.id}> room is updated`);
Didn't Joe ask me to change that the last time?

2021-01-05 08:52 UTC, kawaijoe approved these changes
LGTM

2021-01-06 04:10 UTC, Pante approved these changes
LGTM

2021-01-10 06:53 UTC, merged