poke-client
forus-labs/poke pull request #6
Opened 2021-01-12 13:12 UTC by Daviiddoo

2021-01-12 15:01 UTC, Pante requested changes
There's a few more minor issues, but I highlighted the more major ones for now.

2021-01-12 15:01 UTC, Pante commented on client/src/connection.ts
> +        console.error(error);
This seems off, what will be returned if an error is thrown?

2021-01-14 14:18 UTC, kawaijoe requested changes

2021-01-14 14:18 UTC, kawaijoe commented on README.md
> +## Client
I think `Javascript Testing Client` is a better name. Ideally, there will be many clients.

2021-01-14 14:18 UTC, kawaijoe commented on client/src/connection.ts
> +    const socket = io('http://127.0.0.1:3000', {//process.env.URL, {
And what's that comment at the end for?

2021-01-14 14:18 UTC, kawaijoe commented on client/src/connection.ts
> +    });
Wait that's all it does? We can't manually broadcast additional messages?

2021-01-14 14:18 UTC, kawaijoe commented on client/src/connection.ts
> +        console.log('user disconnected: ', socket.id);
Can you please ensure consistency between your log statements?

2021-01-14 14:18 UTC, kawaijoe commented on client/src/connection.ts
> +        socket.emit('message', 'hello from client');
Also, does the server accept strings? I thought it was some raw bytes.

2021-01-18 15:14 UTC, Daviiddoo commented on client/src/connection.ts
> +        socket.emit('message', 'hello from client');
It can except any type of data.

2021-04-27 12:01 UTC, kawaijoe requested changes
Quite a fair bit of formatting issues. Please review all formatting issues before submitting a PR!

2021-04-27 12:01 UTC, kawaijoe commented on client/src/connection.ts
> +            process.stdout.write('message: ');
May I know what is the point of this line? And also why use `process.stdout.write(...)` instead of `console.log(...)`?

2021-04-29 14:01 UTC, Daviiddoo commented on client/src/connection.ts
> +            process.stdout.write('message: ');
It is to adjust the formatting of the console messages. `console.log(...)` ends with `\n` while `process.stdout.write(...)` does not.

2021-04-29 14:05 UTC, Daviiddoo commented on client/src/client.ts
> +const testConnection = async () => {
I am waiting for @Pante comment

2021-04-30 01:21 UTC, Pante requested changes

2021-04-30 01:21 UTC, Pante commented on client/src/client.ts
> +        process.exit(0);
Must we explicitly exit?

2021-04-30 01:21 UTC, Pante commented on client/src/client.ts
> +const testConnection = async () => {
maybe tryConnect?

2021-04-30 01:21 UTC, Pante commented on client/src/connection.ts
> +            resolve(token);
we can merge line 18 and 19 without declaring a new variable.

2021-04-30 01:21 UTC, Pante commented on client/src/connection.ts
> +            terminal.question('message: ', (msg) => {
it's minor but I think we can use the shorthand here.

2021-04-30 01:21 UTC, Pante commented on client/src/connection.ts
> +        try {
the `try-catch` can be moved outside to surround the while loop.

2021-04-30 05:49 UTC, kawaijoe commented on client/src/client.ts
> +const testConnection = async () => {
Sounds good.

2021-04-30 05:53 UTC, kawaijoe commented on client/src/connection.ts
> +            process.stdout.write('message: ');
Fair enough, that still doesn't explain why this line is here though. Why did you decide to print "message" here? It seems really out of place and random.

2021-05-03 15:58 UTC, Daviiddoo commented on client/src/client.ts
> +        process.exit(0);
The app won't close without the explicit exit

2021-05-04 00:51 UTC, Pante commented on client/src/client.ts
> +        process.exit(0);
Fair enough

2021-05-04 02:22 UTC, Pante approved these changes

2021-05-07 17:46 UTC, kawaijoe requested changes
Sorry for the delayed review, spotted a few more errors. Please go through the code to ensure there aren't any more formatting issues.

2021-05-07 17:46 UTC, kawaijoe commented on client/src/client.ts
> +        //process.exit(0);
May I know why is this line commented? If it is unnecessary, please remove it.

2021-05-07 17:46 UTC, kawaijoe commented on client/src/connection.ts
> +    catch (error) {
Please format file?

2021-05-19 00:11 UTC, Pante approved these changes

2021-06-01 09:42 UTC, merged